#!/usr/bin/env python3

"""
prepare_arxiv.py

Prepare a LaTeX project for arXiv submission.

What it does:
  1. Compiles the original project with -recorder to determine which local
     files are actually used.
  2. Creates a NEW output directory containing only those required files.
  3. Flattens all required files into that directory.
  4. Rewrites common LaTeX references to use flattened filenames.
  5. Removes comments from all .tex files.
  6. Does not copy hidden files/directories or common LaTeX build artifacts.
  7. Appends the requested arXiv four-pass trigger after \\end{document}.

The original project is not modified.

Usage:
    python3 prepare_arxiv.py /path/to/project

or:

    python3 prepare_arxiv.py /path/to/project \
        --main paper.tex \
        --output /path/to/arxiv_submission

Requirements:
    pdflatex

Optional but recommended:
    latexmk
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import tarfile
from pathlib import Path


# Files generated by ordinary LaTeX builds and not wanted in the submission.
#
# .bbl is deliberately NOT included here. A .bbl can be an actual required
# input to the final document and is commonly useful/necessary on arXiv.
GENERATED_EXTENSIONS = {
    ".aux",
    ".log",
    ".out",
    ".toc",
    ".lof",
    ".lot",
    ".blg",
    ".fls",
    ".fdb_latexmk",
    ".synctex",
    ".nav",
    ".snm",
    ".vrb",
    ".bcf",
    ".run.xml",
    ".xdv",
    ".dvi",
    ".ps",
}

GENERATED_NAMES = {
    "missfont.log",
    "texput.log",
}

ARXIV_TYPEOUT = (
    r"\typeout{get arXiv to do 4 passes: "
    r"Label(s) may have changed. Rerun}"
)


def die(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    sys.exit(1)


def warn(message: str) -> None:
    print(f"WARNING: {message}", file=sys.stderr)


def is_hidden_relative(path: Path, root: Path) -> bool:
    """True if any component below root starts with '.'."""
    try:
        rel = path.relative_to(root)
    except ValueError:
        return False

    return any(part.startswith(".") for part in rel.parts)


def is_generated_file(path: Path) -> bool:
    name = path.name.lower()

    if name in GENERATED_NAMES:
        return True

    # Handle things such as file.synctex.gz.
    if name.endswith(".synctex.gz"):
        return True

    for ext in GENERATED_EXTENSIONS:
        if name.endswith(ext):
            return True

    # Rendered PDFs should not be submitted unless they are themselves
    # included as figures. We therefore don't globally reject .pdf here;
    # the .fls dependency information decides whether a PDF is required.
    return False


def run_compile(project: Path, main: Path) -> Path:
    """
    Compile with recorder enabled and return the .fls path.

    Prefer latexmk if available because it can resolve bibliography and
    references before we inspect dependencies.
    """
    print(f"[1/6] Recording LaTeX dependencies from {main.name} ...")

    latexmk = shutil.which("latexmk")

    if latexmk:
        cmd = [
            latexmk,
            "-pdf",
            "-interaction=nonstopmode",
            "-file-line-error",
            "-recorder",
            main.name,
        ]
    else:
        pdflatex = shutil.which("pdflatex")
        if not pdflatex:
            die("Neither 'latexmk' nor 'pdflatex' was found in PATH.")

        warn(
            "latexmk not found. Running pdflatex directly. "
            "Bibliography-generated dependencies may be less reliably detected."
        )

        cmd = [
            pdflatex,
            "-interaction=nonstopmode",
            "-file-line-error",
            "-recorder",
            main.name,
        ]

    result = subprocess.run(
        cmd,
        cwd=project,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )

    if result.returncode != 0:
        print(result.stdout)
        die(
            "The project did not compile successfully. "
            "Fix the original project before preparing the arXiv directory."
        )

    fls = project / (main.stem + ".fls")

    if not fls.exists():
        die(f"LaTeX did not produce expected recorder file: {fls}")

    return fls


def parse_fls(fls: Path, project: Path) -> set[Path]:
    """
    Read project-local INPUT files from a LaTeX .fls recorder file.
    """
    print("[2/6] Finding files actually used by the document ...")

    project = project.resolve()
    used: set[Path] = set()

    with fls.open("r", encoding="utf-8", errors="replace") as f:
        for line in f:
            if not line.startswith("INPUT "):
                continue

            raw = line[6:].strip()
            if not raw:
                continue

            candidate = Path(raw)

            if not candidate.is_absolute():
                candidate = project / candidate

            try:
                candidate = candidate.resolve(strict=False)
            except OSError:
                continue

            try:
                candidate.relative_to(project)
            except ValueError:
                # System TeX files, fonts, etc.
                continue

            if candidate.is_file():
                used.add(candidate)

    return used


def explicitly_referenced_bibliography_files(
    project: Path, files: set[Path]
) -> set[Path]:
    """
    Add .bib files named in bibliography commands.

    Bib files are not always visible as pdflatex INPUT records because BibTeX
    or Biber may consume them rather than pdflatex itself.
    """
    result: set[Path] = set()

    tex_files = [p for p in files if p.suffix.lower() == ".tex"]

    patterns = [
        # \bibliography{foo,bar}
        re.compile(r"\\bibliography\s*\{([^}]*)\}"),
        # \addbibresource[...]{foo.bib}
        re.compile(r"\\addbibresource(?:\s*\[[^\]]*\])?\s*\{([^}]*)\}"),
    ]

    for tex in tex_files:
        try:
            text = tex.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue

        # Old BibTeX syntax
        for match in patterns[0].finditer(text):
            for item in match.group(1).split(","):
                item = item.strip()
                if not item:
                    continue

                p = Path(item)
                if p.suffix == "":
                    p = p.with_suffix(".bib")

                candidate = (tex.parent / p).resolve()
                if candidate.is_file():
                    result.add(candidate)

        # biblatex
        for match in patterns[1].finditer(text):
            item = match.group(1).strip()
            if not item:
                continue

            candidate = (tex.parent / item).resolve()
            if candidate.is_file():
                result.add(candidate)

    return result


def validate_flattening(files: set[Path]) -> dict[str, Path]:
    """
    Ensure no two required files have the same basename.

    Flattening would otherwise overwrite one of them.
    """
    print("[3/6] Checking whether the project can be flattened safely ...")

    by_name: dict[str, Path] = {}
    conflicts: dict[str, list[Path]] = {}

    for src in sorted(files):
        name = src.name

        if name in by_name and by_name[name] != src:
            conflicts.setdefault(name, [by_name[name]]).append(src)
        else:
            by_name[name] = src

    if conflicts:
        lines = [
            "",
            "The project cannot be flattened safely because different files",
            "have the same basename:",
            "",
        ]

        for name, paths in conflicts.items():
            lines.append(f"  {name}")
            for p in paths:
                lines.append(f"      {p}")
            lines.append("")

        lines += [
            "Rename these files in the original project so every required",
            "file has a unique basename, then run this script again.",
        ]

        die("\n".join(lines))

    return by_name


def strip_latex_comments(text: str) -> str:
    """
    Remove ordinary LaTeX comments while preserving escaped percent signs.

    A '%' starts a comment when preceded by an even number of consecutive
    backslashes. Thus:
        % comment
        text % comment
    are stripped, while:
        50\\%
    is preserved.

    This intentionally works line-by-line and does not attempt to implement
    the complete TeX tokenizer.
    """
    output = []

    for line in text.splitlines(keepends=True):
        newline = ""

        if line.endswith("\r\n"):
            body = line[:-2]
            newline = "\n"
        elif line.endswith("\n") or line.endswith("\r"):
            body = line[:-1]
            newline = "\n"
        else:
            body = line

        comment_pos = None

        for i, char in enumerate(body):
            if char != "%":
                continue

            backslashes = 0
            j = i - 1

            while j >= 0 and body[j] == "\\":
                backslashes += 1
                j -= 1

            if backslashes % 2 == 0:
                comment_pos = i
                break

        if comment_pos is not None:
            body = body[:comment_pos]

        # Remove whitespace that existed only immediately before a comment.
        body = body.rstrip()

        # Don't keep completely empty comment-only lines.
        if body:
            output.append(body + newline)
        elif comment_pos is None:
            output.append(newline)

    return "".join(output)


def rewrite_references(
    text: str,
    source_file: Path,
    project: Path,
    used_files: set[Path],
) -> str:
    """
    Rewrite common file references after all dependencies are moved to root.

    We resolve each reference relative to the original .tex file where
    possible, then replace it with the dependency's basename.
    """

    used_resolved = {p.resolve(): p for p in used_files}

    def resolve_ref(raw: str, extensions: tuple[str, ...]) -> str | None:
        raw = raw.strip()

        if not raw:
            return None

        # Don't alter macro-generated/dynamic paths.
        if any(c in raw for c in ("\\", "#", "$")):
            return None

        candidate_raw = Path(raw)

        candidates = []

        if candidate_raw.suffix:
            candidates.append(source_file.parent / candidate_raw)
        else:
            candidates.append(source_file.parent / candidate_raw)
            for ext in extensions:
                candidates.append(
                    source_file.parent / (str(candidate_raw) + ext)
                )

        for candidate in candidates:
            resolved = candidate.resolve()

            if resolved in used_resolved:
                original_had_extension = candidate_raw.suffix != ""

                if original_had_extension:
                    return used_resolved[resolved].name

                # Keep extensionless syntax for \input{foo}, etc.
                return Path(used_resolved[resolved].name).stem

        # Fallback: if it contains directories, flatten textual reference to
        # basename. This is useful for graphic extensions LaTeX resolves later.
        if "/" in raw:
            return Path(raw).name

        return None

    # \input{...} and \include{...}
    def repl_tex(match: re.Match) -> str:
        command = match.group(1)
        raw = match.group(2)

        replacement = resolve_ref(raw, (".tex",))

        return (
            f"\\{command}{{{replacement}}}"
            if replacement
            else match.group(0)
        )

    text = re.sub(
        r"\\(input|include)\s*\{([^{}]+)\}",
        repl_tex,
        text,
    )

    # \includegraphics[options]{...}
    def repl_graphics(match: re.Match) -> str:
        options = match.group(1) or ""
        raw = match.group(2)

        replacement = resolve_ref(
            raw,
            (
                ".pdf",
                ".png",
                ".jpg",
                ".jpeg",
                ".eps",
                ".mps",
            ),
        )

        return (
            f"\\includegraphics{options}{{{replacement}}}"
            if replacement
            else match.group(0)
        )

    text = re.sub(
        r"\\includegraphics(\s*\[[^\]]*\])?\s*\{([^{}]+)\}",
        repl_graphics,
        text,
    )

    # \lstinputlisting[...]{...}
    def repl_listing(match: re.Match) -> str:
        options = match.group(1) or ""
        raw = match.group(2)

        replacement = resolve_ref(raw, ("",))

        return (
            f"\\lstinputlisting{options}{{{replacement}}}"
            if replacement
            else match.group(0)
        )

    text = re.sub(
        r"\\lstinputlisting(\s*\[[^\]]*\])?\s*\{([^{}]+)\}",
        repl_listing,
        text,
    )

    # \addbibresource[...]{...}
    def repl_addbib(match: re.Match) -> str:
        options = match.group(1) or ""
        raw = match.group(2)

        replacement = resolve_ref(raw, (".bib",))

        return (
            f"\\addbibresource{options}{{{replacement}}}"
            if replacement
            else match.group(0)
        )

    text = re.sub(
        r"\\addbibresource(\s*\[[^\]]*\])?\s*\{([^{}]+)\}",
        repl_addbib,
        text,
    )

    # \bibliography{a,b,c}
    def repl_bibliography(match: re.Match) -> str:
        pieces = []

        for raw in match.group(1).split(","):
            raw = raw.strip()
            replacement = resolve_ref(raw, (".bib",))
            pieces.append(replacement or raw)

        return "\\bibliography{" + ",".join(pieces) + "}"

    text = re.sub(
        r"\\bibliography\s*\{([^{}]+)\}",
        repl_bibliography,
        text,
    )

    # \graphicspath{{figures/}{images/}}
    #
    # Once everything is in one directory this is unnecessary and may cause
    # LaTeX to search nonexistent directories. Remove it.
    text = re.sub(
        r"\\graphicspath\s*\{(?:\s*\{[^{}]*\}\s*)+\}",
        "",
        text,
    )

    return text


def append_arxiv_typeout(text: str) -> str:
    """Append the requested marker once, after \\end{document}."""
    if ARXIV_TYPEOUT in text:
        return text

    # Remove trailing whitespace and append after whatever currently ends
    # the document. TeX ignores material after \end{document}, but arXiv's
    # source analysis sees the typeout trigger.
    return text.rstrip() + "\n\n" + ARXIV_TYPEOUT + "\n"


def make_output(
    project: Path,
    output: Path,
    main: Path,
    files: set[Path],
) -> None:
    print(f"[4/6] Creating clean flat directory: {output}")

    if output.exists():
        shutil.rmtree(output)

    output.mkdir(parents=True)

    for src in sorted(files):
        if is_hidden_relative(src, project):
            # A used hidden input is suspicious enough that silently dropping
            # it could break compilation.
            warn(f"Skipping hidden project file: {src}")
            continue

        if is_generated_file(src):
            continue

        # Don't copy the rendered main-document PDF.
        if src == project / f"{main.stem}.pdf":
            continue

        dest = output / src.name

        if src.suffix.lower() == ".tex":
            text = src.read_text(encoding="utf-8", errors="replace")

            # Strip comments before rewriting.
            text = strip_latex_comments(text)

            text = rewrite_references(
                text=text,
                source_file=src,
                project=project,
                used_files=files,
            )

            if src.resolve() == main.resolve():
                text = append_arxiv_typeout(text)

            dest.write_text(text, encoding="utf-8")

        else:
            shutil.copy2(src, dest)


def compile_output(output: Path, main_name: str) -> None:
    """
    Verify the cleaned directory still compiles and resolves references.
    Leaves the final PDF in place for manual inspection.
    """
    print("[5/6] Verifying flattened submission and resolving references ...")

    latexmk = shutil.which("latexmk")
    if not latexmk:
        die(
            "'latexmk' is required for reliable verification of "
            "bibliography and cross-references. Install it with:\n"
            "    sudo apt install latexmk"
        )

    cmd = [
        latexmk,
        "-pdf",
        "-interaction=nonstopmode",
        "-file-line-error",
        "-halt-on-error",
        main_name,
    ]

    result = subprocess.run(
        cmd,
        cwd=output,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )

    if result.returncode != 0:
        print("\n----- Compilation output -----\n")
        print(result.stdout)
        print("----- End compilation output -----\n")

        die(
            "The flattened project does not compile cleanly. "
            "The output directory has been left in place for inspection."
        )

    print("Compilation succeeded and latexmk completed its required passes.")


def cleanup_output(output: Path, main_stem: str) -> None:
    """
    Clean the verified arXiv source directory.

    Keep:
      - source files needed by arXiv
      - generated .bbl
      - main.pdf for manual verification

    Delete:
      - .bib files
      - other LaTeX-generated files
    """
    print("[6/7] Cleaning final arXiv source ...")

    verification_pdf = f"{main_stem}.pdf"

    for path in list(output.iterdir()):
        if path.is_dir():
            shutil.rmtree(path)
            continue

        # Keep the precompiled bibliography.
        if path.suffix.lower() == ".bbl":
            continue

        # Keep the compiled PDF for manual checking.
        if path.name == verification_pdf:
            continue

        # Remove bibliography source; arXiv gets the .bbl.
        if path.suffix.lower() == ".bib":
            print(f"  deleting bibliography source: {path.name}")
            path.unlink()
            continue

        # Remove other LaTeX-generated files.
        if is_generated_file(path):
            print(f"  deleting generated file: {path.name}")
            path.unlink()

def create_tarball(output: Path, main_stem: str) -> Path:
    """
    Create ax.tar containing the final arXiv submission files.

    Keep main.pdf in the output directory for manual inspection,
    but do not include it in ax.tar.
    """
    print("[7/7] Creating ax.tar ...")

    tar_path = output / "ax.tar"
    verification_pdf = f"{main_stem}.pdf"

    if tar_path.exists():
        tar_path.unlink()

    files = [
        path
        for path in sorted(output.iterdir())
        if path.is_file()
        and path.name != "ax.tar"
        and path.name != verification_pdf
    ]

    with tarfile.open(tar_path, mode="w") as tar:
        for path in files:
            print(f"  adding: {path.name}")
            tar.add(path, arcname=path.name)

    return tar_path

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Prepare a flat, minimal LaTeX project for arXiv."
    )

    parser.add_argument(
        "project",
        type=Path,
        help="Root directory of the existing LaTeX project",
    )

    parser.add_argument(
        "--main",
        default="main.tex",
        help="Main TeX filename, relative to project root (default: main.tex)",
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output directory (default: PROJECT_arxiv)",
    )

    args = parser.parse_args()

    project = args.project.expanduser().resolve()

    if not project.is_dir():
        die(f"Project directory does not exist: {project}")

    main_tex = (project / args.main).resolve()

    if not main_tex.is_file():
        die(f"Main TeX file does not exist: {main_tex}")

    try:
        main_tex.relative_to(project)
    except ValueError:
        die("--main must refer to a file inside the project directory.")

    output = (
        args.output.expanduser().resolve()
        if args.output
        else project.parent / f"{project.name}_arxiv"
    )

    try:
        output.relative_to(project)
    except ValueError:
        pass
    else:
        die(
            "The output directory must not be inside the source project. "
            "Put it next to the project instead."
        )

    # Compile first so the recorder tells us what was actually consumed.
    fls = run_compile(project, main_tex)

    used_files = parse_fls(fls, project)

    # main.tex is obviously required even if something unusual prevented it
    # from appearing in the recorder list.
    used_files.add(main_tex)

    # Bibliography databases can be consumed by BibTeX/Biber rather than
    # directly by pdflatex.
    used_files |= explicitly_referenced_bibliography_files(
        project, used_files
    )

    # Remove hidden paths and ordinary generated files from consideration,
    # with the exception that required PDFs such as figure PDFs remain.
    required = {
        p
        for p in used_files
        if not is_hidden_relative(p, project)
        and not is_generated_file(p)
    }

    # Never retain the already-rendered main-document PDF.
    required.discard(project / f"{main_tex.stem}.pdf")

    validate_flattening(required)

    make_output(
        project=project,
        output=output,
        main=main_tex,
        files=required,
    )

    # The flattened main file is identified by basename.
    flat_main = main_tex.name

    compile_output(output, flat_main)

    # At this point compilation has succeeded, including bibliography and
    # cross-reference processing. The generated .bbl will now be retained.
    cleanup_output(output, main_tex.stem)

    tar_path = create_tarball(output, main_tex.stem)

    print()
    print("Done.")
    print(f"Clean arXiv directory: {output}")
    print(f"Upload tarball:         {tar_path}")
    print()

    print("Final source files:")
    for p in sorted(output.iterdir()):
        if p.name != "ax.tar":
            print(f"  {p.name}")

    print()
    print("Tarball contents:")
    with tarfile.open(tar_path, "r") as tar:
        for member in tar.getmembers():
            print(f"  {member.name}")
    print()
    print("Files included:")
    for p in sorted(output.iterdir()):
        print(f"  {p.name}")
    print()
    print(
        "Review the directory manually before uploading, especially any "
        ".bib, .bbl, .sty, .cls, source-code, or data files."
    )


if __name__ == "__main__":
    main()
